name: 'Setup conan enviorrnement'
description: 'Compile and run unit tests'


runs:
  using: "composite"
  steps:
    - name: "Setup Conan Client"
      uses: conan-io/setup-conan@v1

    - name: "Configure Conan to use libhal's artifactory"
      shell: bash
      run: |
          conan config install https://github.com/libhal/conan-config2.git
          conan hal setup